apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      hostNetwork: false
      hostPID: false
      containers:
      - name: node-exporter
        image: prom/node-exporter:v1.7.0
        args:
          - --path.rootfs=/host
        ports:
        - name: metrics
          containerPort: 9100
        volumeMounts:
        - name: rootfs
          mountPath: /host
          readOnly: true
      volumes:
      - name: rootfs
        hostPath:
          path: /
---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  ports:
  - port: 9100
    targetPort: metrics
  selector:
    app: node-exporter